### ISSUE TITLE
How to bind select_refactor() to a key?

### ISSUE THREAD

**Issue by d33tah** [ThePrimeagen/refactoring.nvim#324] opened 2022-06-22 13:02 UTC
Thanks for creating the plugin! It works nicely when used through `:` command line. Unfortunately I have no idea how to map it to F6. Here's what I tried:

```
vnoremap <F6>    <cmd>lua require('refactoring').select_refactor()<CR>
```

I get the menu, but then I get the following error:

```
E5108: Error executing lua ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ....vim/plugged/refactoring.nvim/lua/refactoring/region.lua:153: attempt to get length of a nil value
stack traceback:
        [C]: in function 'error'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:40: in function 'on_confirm'
        /usr/local/share/nvim/runtime/lua/vim/ui.lua:93: in function 'input'
        ...m/plugged/refactoring.nvim/lua/refactoring/get_input.lua:8: in function 'returned_function'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:26: in function 'callback_or_next'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:113: in function <...ah/.vim/plugged/plenary.nvim/lua/plenary/async/async.lua:112>
        ...ugged/refactoring.nvim/lua/refactoring/pipeline/init.lua:70: in function 'run'
        ...lugged/refactoring.nvim/lua/refactoring/refactor/106.lua:535: in function <...lugged/refactoring.nvim/lua/refactoring/refactor/106.lua:524>
        ...h/.vim/plugged/refactoring.nvim/lua/refactoring/init.lua:31: in function 'refactor'
        ...h/.vim/plugged/refactoring.nvim/lua/refactoring/init.lua:49: in function 'select_refactor'
        [string ":lua"]:1: in main chunk
```

I tried asking on #neovim IRC chat, but unfortunately I got no response there.

**Comment by pranavrao145** [comment] 2022-06-30 23:40
Hi @d33tah. Thanks for opening an issue. Apologies for the late reply, but I just tried this map and it seems to be working for me. Are you still having this issue?

**Comment by d33tah** [comment] 2022-07-01 07:59
@pranavrao145 yup, still having it. Here's my neovim version:

```
NVIM v0.8.0-dev+377-gae02c02f1
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-11 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-protbute=pure -Wsuggest-attribute=const -Wsuggest-attribute=malloc -Wsuggest-attribute=cold -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/cI/home/runner/work/neovim/neovim/.deps/usr/include -I/usr/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az97-493

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```

Let me know if you need any more details.

**Comment by teddylear** [comment] 2022-07-01 16:25
@d33tah Please provide which refactor option you selected from `select_refactors` and a code snippet of what you are trying to refactor. We cannot debug from the current provided information.

**Comment by d33tah** [comment] 2022-07-01 18:35
@teddylear 

Here's a recording:

https://asciinema.org/a/105AndA80LZhtyKhwLtWFx7kO

And here's the codebase:

https://github.com/hakierspejs/ksiemgowy/tree/autocorrect_based_on_reported_balance

I'm ready to provide any more needed information :)

**Comment by teddylear** [comment] 2022-07-01 22:54
@d33tah I found the issue. Currently you don't have any region selected because you are still in visual mode when trying to call `Extract Function` and not in normal mode. For most languages this would result in a "Scope is nil" error, but not for python as I just confirmed locally. So that means for `Extract Function` you need to go from visual mode back to normal mode. I can add a check for Extract Function to make this a more explicit error.

**Comment by teddylear** [comment] 2022-07-07 21:32
@d33tah I merged a fix to this issue making the error much more clear. I'm going to close this issue for now, please re-open if it's not resolved.

**Closed by teddylear** 2022-07-07 21:32 UTC
Labels: question, waiting-reply
