### ISSUE TITLE
Errors on nightly

### ISSUE THREAD

**Issue by rebelot** [ThePrimeagen/refactoring.nvim#140] opened 2021-11-18 20:21 UTC
Hi, I'm using [null-ls](https://github.com/jose-elias-alvarez/null-ls.nvim) and I'm getting this after calling `:'<,'>lua vim.lsp.buf.range_code_action()`

I'm on current nightly 

```
E5108: Error executing lua vim/shared.lua:261: after the second argument: expected table, got nil
stack traceback:
        [C]: in function 'error'
        vim/shared.lua:608: in function 'validate'
        vim/shared.lua:261: in function 'tbl_deep_extend'
        ...ker/opt/refactoring.nvim/lua/refactoring/config/init.lua:39: in function 'merge'
        ...ack/packer/opt/refactoring.nvim/lua/refactoring/init.lua:23: in function 'refactor'
        ...s.nvim/lua/null-ls/builtins/code_actions/refactoring.lua:24: in function 'action'
        .../site/pack/packer/opt/null-ls.nvim/lua/null-ls/state.lua:36: in function 'run_action'
        ...ack/packer/opt/null-ls.nvim/lua/null-ls/code-actions.lua:46: in function 'handler'
        ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:87: in function 'handle'
        ...im/site/pack/packer/opt/null-ls.nvim/lua/null-ls/rpc.lua:103: in function 'request'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:930: in function 'request'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:1337: in function 'fn'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:163: in function 'for_each_buffer_client'
        ...urenzi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp.lua:1336: in function 'request'
        ...zi/usr/src/neovim/share/nvim/runtime/lua/vim/lsp/buf.lua:625: in function 'execute_command'
        ...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:283: in function 'execute_action'
        ...acker/start/telescope.nvim/lua/telescope/builtin/lsp.lua:323: in function 'run_replace_or_original'
        ...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'
        ...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'
        [string ":lua"]:1: in main chunk
pyright: 1: Unsupported command
```

**Comment by jose-elias-alvarez** [comment] 2021-11-19 19:10
To add to this, I don't think the issue is related to null-ls, since I'm getting issues using the [recommended setup](https://github.com/ThePrimeagen/refactoring.nvim#basic-setup) on the latest Neovim master (NVIM v0.6.0-dev+603-g9ec4417af).

**Comment by pranavrao145** [comment] 2021-11-20 04:09
@jose-elias-alvarez this issue was actually solved in #142. I think it should be fixed if you're on 0.6 and you run `:PackerSync` or `:PlugUpdate`.

**Comment by rebelot** [comment] 2021-11-21 09:42
it does not seem to be working, it is "slightly better" (aka, I see the "new var name" prompt and sometimes text changes) if I disable other lsp active for the buffer (i.e pyright). not really usable tho

**Comment by jamestrew** [comment] 2021-11-22 17:53
I am getting a very similar error as well on nvim 0.5.1. Just `PackerSync`'ed as well.
```
packer.nvim: Error running config for refactoring.nvim: vim/shared.lua:219: after the second argument: expected table, got nil                                                             
stack traceback:                                                                                                                                                                           
^Ivim/shared.lua:219: in function 'tbl_deep_extend'                                                                                                                                        
^I...ker/opt/refactoring.nvim/lua/refactoring/config/init.lua:39: in function 'new'                                                                                                        
^I...ker/opt/refactoring.nvim/lua/refactoring/config/init.lua:103: in function 'setup'                                                                                                     
^I...ack/packer/opt/refactoring.nvim/lua/refactoring/init.lua:7: in function 'setup'                                                                                                       
^I[string "..."]: in function <[string "..."]:0>                                                                                                                                           
^I[C]: in function 'pcall'                                                                                                                                                                 
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:50: in function 'loader_apply_config'                                                                                        
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:145: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:118>                                           
^I[C]: in function 'pcall'                                                                                                                                                                 
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:162: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>                                           
^I[string ":lua"]:1: in main chunk                                                                                                                                                         
^I[C]: at 0x556e786eb530                                                                                                                                                                   
^I[C]: in function 'pcall'                                                                                                                                                                 
^I...acker/start/telescope.nvim/lua/telescope/actions/set.lua:134: in function 'run_replace_or_original'                                                                                   
^I...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'run_replace_or_original'                                                                                    
^I...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'run_replace_or_original'                                                                                    
^I...packer/start/telescope.nvim/lua/telescope/actions/mt.lua:30: in function 'key_func'                                                                                                   
^I...k/packer/start/telescope.nvim/lua/telescope/mappings.lua:235: in function 'execute_keymap'                                                                                            
Press ENTER or type command to continue        
```

**Comment by jamestrew** [comment] 2021-11-22 18:00
This is the last commit that doesn't error out for me [41caf9d207887779255fa659a2ddb2182b158e3b](https://github.com/ThePrimeagen/refactoring.nvim/commit/41caf9d207887779255fa659a2ddb2182b158e3b)

Starting the [next commit](https://github.com/ThePrimeagen/refactoring.nvim/commit/3e3fb7ecb237f6c7cb61cc9f850634ef7ec2d2b6) I get this:
```
packer.nvim: Error running config for refactoring.nvim: vim/shared.lua:219: after the second argument: expected table, got nil                                                             
stack traceback:                                                                                                                                                                           
^Ivim/shared.lua:219: in function 'tbl_deep_extend'                                                                                                                                        
^I...ker/opt/refactoring.nvim/lua/refactoring/config/init.lua:30: in function 'new'                                                                                                        
^I...ker/opt/refactoring.nvim/lua/refactoring/config/init.lua:86: in function 'setup'                                                                                                      
^I...ack/packer/opt/refactoring.nvim/lua/refactoring/init.lua:7: in function 'setup'                                                                                                       
^I[string "..."]: in function <[string "..."]:0>                                                                                                                                           
^I[C]: in function 'pcall'                                                                                                                                                                 
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:50: in function 'loader_apply_config'                                                                                        
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:145: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:118>                                           
^I[C]: in function 'pcall'                                                                                                                                                                 
^I...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:162: in function <...m/site/pack/packer/start/packer.nvim/lua/packer/load.lua:161>                                           
^I[string ":lua"]:1: in main chunk                                                                                                                                                         
^I[C]: in function 'nvim_set_current_buf'                                                                                                                                                  
^I...e/nvim/site/pack/packer/start/harpoon/lua/harpoon/ui.lua:170: in function 'nav_file'                                                                                                  
Press ENTER or type command to continue        
```
and it looks like that commit changed how the config is setup so not too surprising.

**Comment by ThePrimeagen** [comment] 2021-11-24 01:42
there has been a few new commits since this.  I'll make sure I check out the latest nvim and try to repro

**Comment by teddylear** [comment] 2021-11-26 16:46
^ Second this nightly and latest should be stable as of now.

**Comment by jamestrew** [comment] 2021-11-27 01:48
I found the issue (for me at least) to be related calling `require('refactoring').setup()` with no `opts` as opposed to `require('refactoring').setup({})`. I'll open a PR to handle the no `opts` condition since I feel like many other plugins, including refactoring.nvim prior to commit I mentioned above, could handle a no `opts` setup call.

**Comment by ThePrimeagen** [comment] 2021-11-27 04:02
Are we able to close this?

**Comment by jamestrew** [comment] 2021-11-27 05:04
Good on my end :+1:

**Comment by pranavrao145** [comment] 2021-11-28 02:45
Everything works with both versions on my end as well, I think we're good to close this.

**Comment by teddylear** [comment] 2021-11-28 17:35
I'll close issue for now then. @rebelot Please let us know if this persists on nightly and I can reopen. I've updated README saying that nightly is required.

**Closed by teddylear** 2021-11-28 17:35 UTC
