### ISSUE TITLE
Scope is nil

### ISSUE THREAD

**Issue by jrock2004** [ThePrimeagen/refactoring.nvim#12] opened 2021-08-01 01:47 UTC
Not sure if you are ready for issues, if not just close. I took the example config and when I try any of the options I get

![image](https://user-images.githubusercontent.com/655716/127756562-73ebd5ae-3c60-4f96-98a5-b90610e119f7.png)

**Comment by ThePrimeagen** [comment] 2021-08-01 16:01
Yes this is something I need to fix. I'm going to try to fix it either today or in a little bit. 

Could you give me the exact code you had and it's exact highlighted region?

**Comment by jrock2004** [comment] 2021-08-01 16:04
![image](https://user-images.githubusercontent.com/655716/127777641-dda04b53-90e8-41b4-a26f-a63714a00bd9.png)

Code just in case you want to copy to test

```js
let output = "";
if (Application("Music").running()) {
  const track = Application("Music").currentTrack,
    artist = track.artist(),
    title = track.name();

  output = `${title} - ${artist}`.substr(0, 50);
} else if (Application("Spotify").running()) {
  const track = Application("Spotify").currentTrack,
    artist = track.artist(),
    title = track.name();

  output = `${title} - ${artist}`.substr(0, 50);
} else if (Application("iTunes").isRunning()) {
  const track = Application("iTunes").currentTrack,
    artist = track.artist(),
    title = track.name();

  output = `${title} - ${artist}`.substr(0, 50);
}

output;
```

I get the same error in Lua files as well

**Comment by ThePrimeagen** [comment] 2021-08-01 16:11
Of course! This will be a great test.

**Comment by danielnehrig** [comment] 2021-08-02 13:58
@ThePrimeagen afaik this error only occurs if you enter visual mode the first time
so means:
if you do visual mode then normal mode then visual mode and then trigger refactoring there will be no error

https://streamable.com/qkccdm

**Comment by jrock2004** [comment] 2021-08-02 16:54
@danielnehrig Let me try this because I think I tried this and was not so lucky

**Comment by ThePrimeagen** [comment] 2021-08-03 02:19
interesting.

I have added a bunch of testing.  This should allow for this to work.

Checkout #18 #16 for the new testing harness.  I can translate your highlight and your code and create a failing test :)

**Comment by jrock2004** [comment] 2021-08-05 18:38
Updated and now running again and see

![image](https://user-images.githubusercontent.com/655716/128403452-8f02ccb8-d44e-4e0a-b88b-d45faa402946.png)

**Comment by max397574** [comment] 2021-08-07 08:42
Have you got TreeSitter?

**Comment by jrock2004** [comment] 2021-08-07 14:28
> Have you got TreeSitter? (and the parser for your langugage)

Yes

**Comment by cds-amal** [comment] 2021-08-08 02:16
I have the same issue :(
<img width="1271" alt="refactor-screen" src="https://user-images.githubusercontent.com/2529600/128618541-3959753f-941f-49b6-b658-ae256f0ed4bc.png">

**Comment by seblj** [comment] 2021-08-15 16:40
> @ThePrimeagen afaik this error only occurs if you enter visual mode the first time
> so means:
> if you do visual mode then normal mode then visual mode and then trigger refactoring there will be no error
> 
> https://streamable.com/qkccdm

I also have this exact same problem

**Comment by ThePrimeagen** [comment] 2021-08-15 17:46
There we go!!! Examples are great! There is the problem!! Make sure you're up to date because I thought I've already fixed this. But to explain the problem here it is.

The top node must not be `(program)`.

[Current definition](https://github.com/ThePrimeagen/refactoring.nvim/blob/master/queries/typescript/refactoring.scm#L18)

I'll make a PR fixing this very soon. This should be easy.

**Comment by seblj** [comment] 2021-08-15 18:08
I actually think that the problem is in region.lua in the function `get_selection_range`. I think this is because something isn't updated right away. Check `:h line()` to see what I mean. I am currently looking into this, but I can't seem to find another way to get the rows and columns

**Comment by seblj** [comment] 2021-08-15 18:14
To follow up: What `get_selection_range` is doing now is taking the last visual range and getting the lines and column of that. So that could result in some strange behaviour. And the on the first visual range, it has no previous, therefore resulting in start_row, end_row, start_col and end_col all being 0

**Comment by seblj** [comment] 2021-08-15 18:22
Ok, it was a pretty easy fix for this on my part. I had to escape the visual-mode in the mapping before running the function. So if you are for example using the mapping from the README, they could be modified to escape before running the function like this.

```Lua
vim.api.nvim_set_keymap("v", "<Leader>re", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("v", "<Leader>rf", [[ <Esc><Cmd>lua require('refactoring').refactor('Extract Function To File')<CR>]], {noremap = true, silent = true, expr = false})
vim.api.nvim_set_keymap("v", "<Leader>rt", [[ <Esc><Cmd>lua M.refactors()<CR>]], {noremap = true, silent = true, expr = false})
```

**Comment by ThePrimeagen** [comment] 2021-08-15 18:24
Would it be reasonable to execute and escape command from within the selection setup task?

**Comment by jrock2004** [comment] 2021-08-15 18:27
@seblj So I updated my keymap to what you have and when I use the code I originally posted I get 

![image](https://user-images.githubusercontent.com/655716/129488628-cf76d249-8fe7-4385-88e1-bd53d5a6bf77.png)

**Comment by ThePrimeagen** [comment] 2021-08-15 18:29
@jrock2004 this one is easy to fix. There is no query language yet for JavaScript in this project. You could provide the exact same scheme definition for JavaScript as there is for typescript and everything would just work out of the box. If not I'll fix this shortly.

**Comment by seblj** [comment] 2021-08-15 18:30
> Would it be reasonable to execute an escape command from within the selection setup task?

Yes I believe so, because the way you are getting the start_row, start_col, end_row and end_col all depends on the marks of the previous visual range is set. And those are not set before exiting visual mode. Therefore, we need to escape visual mode to be able to get the rows and columns correctly

**Comment by jrock2004** [comment] 2021-08-15 18:31
![image](https://user-images.githubusercontent.com/655716/129488689-7548014a-b393-4fb2-a2d7-7e7256445e6e.png)

Ah so maybe we should get which filetypes are supported

**Comment by seblj** [comment] 2021-08-15 18:33
> > Would it be reasonable to execute an escape command from within the selection setup task?
> 
> Yes I believe so, because the way you are getting the start_row, start_col, end_row and end_col all depends on that the marks of the previous visual range is set. And those are not set before exiting visual mode. Therefore, we need to escape visual mode to be able to get the rows and columns correctly

I just read the question again, and maybe I misunderstood? If it looked like I misunderstood, please specify 😅

**Comment by seblj** [comment] 2021-08-15 18:38
> Ah so maybe we should get which filetypes are supported

The README should probably have the filetypes supported, but since this project is pretty new I assume he hasn't had time to add them there yet. However, to easily see the language that is worked on at the moment you could look inside the query folder. All the languages supported should have a folder inside there

**Comment by samrath2007** [comment] 2021-08-24 05:48
Doesn't work at all with python for me.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/69572668/130562819-f3847789-bd2a-4c3c-b626-fc68fb9f64df.png">
I tried selecting everything in the print statement bracket on line 11.

**Comment by pranavrao145** [comment] 2022-01-15 21:33
I think this issue was primarily a result of certain missing queries that have since been added for all languages. Are we good to close this issue?

**Comment by teddylear** [comment] 2022-02-03 13:39
@jrock2004 Closing issue, please let us know if this is still an issue and we can reopen.

**Closed by teddylear** 2022-02-03 13:39 UTC
Labels: bug

**Comment by danielnehrig** [comment] 2022-05-14 23:43
im still experiencing this issue on stable 0.7.0 with current master refactoring plugin video attached and error msg

```
E5108: Error executing lua ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: The coroutine failed with this message: ...start/refactoring.nvim/lua/refactoring/pipeline/init.lua:6
1: Scope is nil
stack traceback:
        [C]: in function 'error'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:14: in function 'callback_or_next'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:40: in function 'step'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:43: in function 'execute'
        ...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:113: in function <...ck/packer/start/plenary.nvim/lua/plenary/async/async.lua:112>
        ...start/refactoring.nvim/lua/refactoring/pipeline/init.lua:70: in function 'run'
        .../start/refactoring.nvim/lua/refactoring/refactor/106.lua:535: in function <.../start/refactoring.nvim/lua/refactoring/refactor/106.lua:524>
        ...k/packer/start/refactoring.nvim/lua/refactoring/init.lua:31: in function 'refactor'
        ...factoring.nvim/lua/telescope/_extensions/refactoring.lua:9: in function 'key_func'
        ...ack/packer/opt/telescope.nvim/lua/telescope/mappings.lua:242: in function 'execute_keymap'
```

https://user-images.githubusercontent.com/4050749/168451492-579d3047-0a4f-47f3-a72e-738d5a3e2a49.mp4

**Comment by teddylear** [comment] 2022-05-15 13:18
@danielnehrig From that video it looks like you are going into visual mode, but not back to normal mode before executing a refactor operation as listed like this command in the README: 
```
vim.api.nvim_set_keymap(
	"v",
	"<leader>rr",
	"<Esc><cmd>lua require('telescope').extensions.refactoring.refactors()<CR>",
	{ noremap = true }
)
```

I believe this should resolve the immediate issue. If this is still an issue, please open up a new issue as this thread already covers multiple issues making it harder for us to track. In the new issue also include your configuration for the plugin as well along with remaps to make things more clear. Also unrelated but a possible issue for you using the plugin in the future, we only test using nightly builds of neovim and not stable, so you may want to use the nightly build to avoid issues going forward.
