### ISSUE TITLE
[Feature] `Incremental Command Preview` usage

### ISSUE THREAD

**Issue by Arjun31415** [ThePrimeagen/refactoring.nvim#317] opened 2022-06-05 17:50 UTC
The refactoring plugin could make use of the new feature in nightly for previewing the changes during rename.
A similar plugin which could [inspire](https://github.com/smjonas/inc-rename.nvim)

**Comment by TheLeoP** [comment] 2023-06-24 03:47
I'm working on this feature, but currently there is a blocker on the `nvim-treesitter` side. Fortunately, this will be solved once the rewrite being made on their `main` branch gets merged to `master`

**Comment by bew** [comment] 2023-06-24 11:14
Could you link to the blocker in question or traces of that rewrite?
(it's always a good idea to link to things, so people reading this can follow along, maybe even accelerate it)

**Comment by TheLeoP** [comment] 2023-06-24 14:13
Of course, @bew. [Here](https://github.com/nvim-treesitter/nvim-treesitter/issues/4902) I explain the blocker with a general case (the cache problem makes the refactor work on the preview, but fail if the command is submited).

Then, [here](https://github.com/nvim-treesitter/nvim-treesitter/pull/4952) I made the `locals` module of `nvim-treesitter` work after the rewrite being made on `main` (adressing the cache issue by using the new cache mechanism of `nvim-treesitter`).

So, the issue is solved on the `main` branch, but not on the `master` branch.

**Closed** 2023-07-14 20:37 UTC
Labels: feature
