### ISSUE TITLE
[Bug] 123: Inline var replaces Python named arguments, which causes SyntaxError

### ISSUE THREAD

**Issue by ColinKennedy** [ThePrimeagen/refactoring.nvim#451] opened 2024-05-05 18:35 UTC
Given this file

```python
class Foo(object):
    def __init__(self, blah=None):
        blah = "something"
        do_thing(blah)

        super(Foo, self).__init__(something, another=another, stuff=stuff, blah=blah)
```

Type `viw` to select all of `blah`. Then call `'<,'>Refactor inline_var`

## Expected
```python
class Foo(object):
    def __init__(self, blah=None):

        do_thing("something")

        super(Foo, self).__init__(something, another=another, stuff=stuff, blah="something")
```

## Actual
```python
class Foo(object):
    def __init__(self, "something"=None):

        do_thing("something")

        super(Foo, self).__init__(something, another=another, stuff=stuff, "something"="something")
```

The above result is a Python syntax error.

Edit: By the way, even if you remove `blah=None` from `    def __init__(self, blah=None):`, the `super(Foo, self).__init__(..., "something"="something")` still remains

**Comment by TheLeoP** [comment] 2024-05-07 00:49
The problem is that we are using the `local.reference` capture to look for the possible references to a variable

https://github.com/ThePrimeagen/refactoring.nvim/blob/d2786877c91aa409c824f27b4ce8a9f560dda60a/lua/refactoring/ts-locals.lua#L389

the nvim-treesitter repo defines said capture for python in [the following way](https://github.com/nvim-treesitter/nvim-treesitter/blob/268611e3ece8463bfb5b09044dcd1b76a28ffbb6/queries/python/locals.scm#L124C1-L124C30)

```scheme
(identifier) @local.reference
```

the python syntax tree for the example code is the following

```scheme
(module ; [0, 0] - [6, 0]
  (class_definition ; [0, 0] - [5, 92]
    name: (identifier) ; [0, 6] - [0, 9]
    superclasses: (argument_list ; [0, 9] - [0, 17]
      (identifier)) ; [0, 10] - [0, 16]
    body: (block ; [1, 4] - [5, 92]
      (function_definition ; [1, 4] - [5, 92]
        name: (identifier) ; [1, 8] - [1, 16]
        parameters: (parameters ; [1, 16] - [1, 33]
          (identifier) ; [1, 17] - [1, 21]
          (default_parameter ; [1, 23] - [1, 32]
            name: (identifier) ; [1, 23] - [1, 27]
            value: (none))) ; [1, 28] - [1, 32]
        body: (block ; [3, 8] - [5, 92]
          (expression_statement ; [3, 8] - [3, 29]
            (call ; [3, 8] - [3, 29]
              function: (identifier) ; [3, 8] - [3, 16]
              arguments: (argument_list ; [3, 16] - [3, 29]
                (string ; [3, 17] - [3, 28]
                  (string_start) ; [3, 17] - [3, 18]
                  (string_content) ; [3, 18] - [3, 27]
                  (string_end))))) ; [3, 27] - [3, 28]
          (expression_statement ; [5, 8] - [5, 92]
            (call ; [5, 8] - [5, 92]
              function: (attribute ; [5, 8] - [5, 33]
                object: (call ; [5, 8] - [5, 24]
                  function: (identifier) ; [5, 8] - [5, 13]
                  arguments: (argument_list ; [5, 13] - [5, 24]
                    (identifier) ; [5, 14] - [5, 17]
                    (identifier))) ; [5, 19] - [5, 23]
                attribute: (identifier)) ; [5, 25] - [5, 33]
              arguments: (argument_list ; [5, 33] - [5, 92]
                (identifier) ; [5, 34] - [5, 43]
                (keyword_argument ; [5, 45] - [5, 60]
                  name: (identifier) ; [5, 45] - [5, 52]
                  value: (identifier)) ; [5, 53] - [5, 60]
                (keyword_argument ; [5, 62] - [5, 73]
                  name: (identifier) ; [5, 62] - [5, 67]
                  value: (identifier)) ; [5, 68] - [5, 73]
                (keyword_argument ; [5, 75] - [5, 91]
                  name: (identifier) ; [5, 75] - [5, 79]
                  value: (string ; [5, 80] - [5, 91]
                    (string_start) ; [5, 80] - [5, 81]
                    (string_content) ; [5, 81] - [5, 90]
                    (string_end))))))))))) ; [5, 90] - [5, 91]
```

the relevant part being line 41: `name: (identifier) ; [5, 75] - [5, 79]`. It could be possible to distinguish this capture from other types of variable references, but a PR would have to be sended upstream (nvim-treesitter) improving the Python `locals.scm` captures. This would look like using more specifig captures (i.e. not `(identifier) @local.reference`) for local references (and this captures should not inlude things like a kwargs, like in this case). I don't know if there is a specific reason to use this capture upstream or if the reason is simply that no one has contributed better python captures yet.

**Comment by ColinKennedy** [comment] 2024-05-07 01:08
So to summarize, you think that stricter locals.scm is needed so that the only the right `(identifier)` of `(keyword_argument (identifier) (identifier))` is matched. I think that's reasonable.


Btw it looks like the Lua locals capture has the same problem

```lua
local blah = 123

local data = { blah = blah }
```

```scm
(chunk ; [0, 0] - [3, 0]
  local_declaration: (variable_declaration ; [0, 0] - [0, 16]
    (assignment_statement ; [0, 6] - [0, 16]
      (variable_list ; [0, 6] - [0, 10]
        name: (identifier)) ; [0, 6] - [0, 10]
      (expression_list ; [0, 13] - [0, 16]
        value: (number)))) ; [0, 13] - [0, 16]
  local_declaration: (variable_declaration ; [2, 0] - [2, 28]
    (assignment_statement ; [2, 6] - [2, 28]
      (variable_list ; [2, 6] - [2, 10]
        name: (identifier)) ; [2, 6] - [2, 10]
      (expression_list ; [2, 13] - [2, 28]
        value: (table_constructor ; [2, 13] - [2, 28]
          (field ; [2, 15] - [2, 26]
            name: (identifier) ; [2, 15] - [2, 19]
            value: (identifier))))))) ; [2, 22] - [2, 26]
```

Replacing `blah` affects both the key and value, which wouldn't make sense because the key `blah` is literally text but the right side of the lua table `blah` refers to the value of blah, not the word itself.

**Comment by TheLeoP** [comment] 2024-05-07 01:17
> So to summarize, you think that stricter locals.scm is needed so that the only the right `(identifier)` of `(keyword_argument (identifier) (identifier))` is matched. Is that right? I think that's reasonable.

Yes, but take into account that:

1. You would need to also handle all the other `local.references` cases left out by using a scricter capture
2. It would be better to first check [the nvim-treesitter docs on locals](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/CONTRIBUTING.md) as well as the [upstream treesitter docs](https://tree-sitter.github.io/tree-sitter/syntax-highlighting#local-variables) because I may be missinterpreting the problem, in which case this would have to be fixed in this plugin instead

> Btw it looks like the Lua locals capture has the same problem

Yes, you are right

**Closed** 2024-07-19 00:47 UTC
Labels: help wanted, waiting-reply
